### ISSUE TITLE
Multi-file project not built after editing

### ISSUE THREAD

**Issue by ktuukkan** [rolandshacks/vs64#13]
When the project code has been split in several files that are included in a main file with `!src`, it seems that changes to included files does not trigger the build correctly. I assume it's trying to build the file that was edited, but due to being included it doesn't have program counter in the beginning, and thus fails in the background. In addition, even when running the main file with `C64: run`, an outdated version is launched. It appears that a change in main file is always required to get a fresh build, which is a bit tedious when working mostly on the included files.

**Comment by paaco** [comment]
Well, I had the same issue with some of my projects as well. I changed all included files to have a `.inc` extension, but you will lose syntax highlighting. After changing any inc file I resaved the asm file to start a build like you describe.

I know it's a little long after your request, but I am working on a PR that would allow you to specify a single file as MAIN file that will always be built, instead of each asm file separately.
