### ISSUE TITLE
Basic support?

### ISSUE THREAD

**Issue by aminta** [rolandshacks/vs64#7]
Do you have in mind to support the BASIC 2.0 too?

**Comment by rosc77** [comment]
Hi,

 

Currently, there are no plans to support BASIC – and it is even questionable how that could possibly work because debugging requires a emulation backend to support those capabilities.

 

 

Von: aminta <notifications@github.com> 
Gesendet: Freitag, 27. September 2019 13:17
An: rosc77/vs64 <vs64@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [rosc77/vs64] Basic support? (#7)

 

Do you have in mind to support the BASIC 2.0 too?
